#ifndef GUARD_CONSTANTS_APRICORN_TREE_H
#define GUARD_CONSTANTS_APRICORN_TREE_H

// Apricorns
#define APRICORN_RED       0
#define APRICORN_BLUE      1
#define APRICORN_YELLOW    2
#define APRICORN_GREEN     3
#define APRICORN_PINK      4
#define APRICORN_WHITE     5
#define APRICORN_BLACK     6

#define APRICORN_COUNT     7

// Trees
#define APRICORN_TREE_NONE 0

#define APRICORN_TREE_ROUTE101_RED_SAPLING 1
#define APRICORN_TREE_ROUTE101_WHITE_TREE 2
#define APRICORN_TREE_ROUTE102_PINK_TREE 3
#define APRICORN_TREE_ROUTE102_BLUE_SAPLING 4
#define APRICORN_TREE_ROUTE102_GREEN_SAPLING 5

#define APRICORN_TREE_COUNT 96

#endif //GUARD_CONSTANTS_APRICORN_TREE_H
